In [1]:
from openpyxl import Workbook

wb = Workbook()

In [2]:
wb.sheetnames

['Sheet']

`active` 속성값을 이용해서 현재 활성화되어 있는 워크시트를 가져온다.

In [3]:
ws = wb.active

워크시트 추가는 `create_sheet()` 메서드를 이용한다. 두 번째 인수로 삽입 위치를 지정할 수도 있다.
좌측 위치는 0부터 시작한다.

In [4]:
ws2 = wb.create_sheet("new_sheet2") # 마지막에 시트 추가
ws1 = wb.create_sheet("new_sheet1", 1) # 두 번째에 시트 삽입

추가된 워크시트들을 확인해보자.

In [5]:
wb.sheetnames

['Sheet', 'new_sheet1', 'new_sheet2']

워크시트를 하나 선택한다.

In [6]:
ws = wb['Sheet']

시트 이름 변경은 `'title'`속성으로 한다.

In [7]:
ws.title = '주소'
ws.title

'주소'

이제 조그마한 표를 하나 만들어보자.
셀에 접근하는 방법은 두 가지 인데, 워크시트에서 셀주소를 지정하는 방법이 있고,

In [8]:
ws['A1'] = '이름'
ws['B1'] = '전화번호'

ws['A2'] = '홍길동'
ws['B2'] = '7777'

워크시트의 `cell()` 메서드로 셀 객체를 직접 다룰 수도 있다.
셀 주소를 'A1'과 같은 심볼이 아니라 숫자 기반의 행열 첨자값으로 셀을 참조할 수 있다.
주의할 점은 행열 첨자 값이 1부터 시작한다는 것이다.

In [9]:
ws.cell(row=3, column=1, value='홍길순');  # A3
ws.cell(row=3, column=2, value='3333');   # B3

다음과 같은 사용도 가능하다.

In [10]:
ws.cell(row=3, column=1).value = '홍길순'  # A3
ws.cell(row=3, column=2).value = '3333'   # B3

cell = ws.cell(row=3, column=1)
cell.value = '홍길순'

이제 파일을 저장한다. 엑셀로 저장된 파일을 직접 확인해보자.

In [11]:
wb.save('address.xlsx')

## openpyxl로 파일 읽기


`openpyxl.load_workbook()`로 파일에서 엑셀 파일을 읽는다.

In [12]:
from openpyxl import load_workbook
wb2 = load_workbook('address.xlsx')
wb2.sheetnames

['주소', 'new_sheet1', 'new_sheet2']

워크시트를 가져오고, 값을 읽어낸다.

In [13]:
sheet = wb2['주소']
sheet['A1'].value

'이름'

데이터가 있는 모든 행과 열에 대해서 반복을 할 수 있다.
실제로 데이터가 있는 영역으로 반복이 한정된다.

In [14]:
for row in sheet.iter_rows():
    for cell in row:
        print(cell, cell.value)

<Cell '주소'.A1> 이름
<Cell '주소'.B1> 전화번호
<Cell '주소'.A2> 홍길동
<Cell '주소'.B2> 7777
<Cell '주소'.A3> 홍길순
<Cell '주소'.B3> 3333


## pandas로 엑셀 파일 읽기


In [15]:
import pandas as pd

df = pd.read_excel('address.xlsx')
df

이름  전화번호
0  홍길동  7777
1  홍길순  3333

In [16]:
df = pd.read_excel('address.xlsx', '주소')

In [17]:
df['이름']

0    홍길동
1    홍길순
Name: 이름, dtype: object

In [18]:
df.iloc[0]

이름       홍길동
전화번호    7777
Name: 0, dtype: object

In [19]:
for index, row in df.iterrows():
    print(index, row[0], row[1])

0 홍길동 7777
1 홍길순 3333


In [20]:
for column in df:
    print(column, list(df[column]))


이름 ['홍길동', '홍길순']
전화번호 [7777, 3333]


In [21]:
arr = df.values
arr

array([['홍길동', 7777],
       ['홍길순', 3333]], dtype=object)

In [22]:
arr[0]

array(['홍길동', 7777], dtype=object)

In [23]:
arr[0][1]

7777

In [24]:
from openpyxl import Workbook
import math
import datetime

wb = Workbook()
ws = wb.active

ws['A1'] = '홍길동'  # 문자열
ws['A2'] = 1234     # 숫자 (int)
ws['A3'] = math.pi  # 숫자 (float)
ws['A4'] = datetime.datetime(2019, 1, 3, 15, 25, 0) # 시간 2019-01-03 15:25:00
ws['A5'] = '=SIN(PI()/2)'  # 수식

wb.save('test.xlsx')

In [25]:
ws['A1':'C2']

((<Cell 'Sheet'.A1>, <Cell 'Sheet'.B1>, <Cell 'Sheet'.C1>),
 (<Cell 'Sheet'.A2>, <Cell 'Sheet'.B2>, <Cell 'Sheet'.C2>))

In [26]:
for row in ws['A1':'C2']:
    print(row)

(<Cell 'Sheet'.A1>, <Cell 'Sheet'.B1>, <Cell 'Sheet'.C1>)
(<Cell 'Sheet'.A2>, <Cell 'Sheet'.B2>, <Cell 'Sheet'.C2>)


In [27]:
data = [(1,2,3),
       (4,5,6)]

for row, drow in zip(ws['A1':'C2'], data):
    for cell, value in zip(row, drow):
        cell.value = value

In [28]:
from openpyxl.utils import get_column_letter

get_column_letter(1)

'A'

In [29]:
def index2cell(row, col):
    return '{}{}'.format(get_column_letter(col), row)

index2cell(row=1,col=3)

'C1'

In [30]:
from openpyxl import Workbook

wb = Workbook()
ws = wb.active

data=[('Id','이름','나이'),
      (1,'홍길동',50),
      (2,'홍길순',60)]

# append all rows
for row in data:
    ws.append(row)
    
wb.save('sample1.xlsx')

In [31]:
from openpyxl import Workbook
import pandas as pd

wb = Workbook()
ws = wb.active

ws.append(('시간',))
data = pd.date_range('2019-1-3 09:00:00', '2019-1-3 15:00:00', freq='10min')

for row in data:
    ws.append((row,))

ws.column_dimensions['A'].width = 18  # 18자(영문기준) 정도 폭으로 설정    
wb.save('test.xlsx')

In [32]:
len(data)

37

In [33]:
data[0]

Timestamp('2019-01-03 09:00:00', freq='10T')

In [34]:
from openpyxl import Workbook
import datetime

wb = Workbook()
ws = wb.active
ws['A1'] = datetime.datetime(2019, 1, 3, 15, 25, 0) # 시간 2019-01-03 15:25:00

ws.column_dimensions['A'].width = 18  # 18자(영문기준) 정도 폭으로 설정
ws.row_dimensions[1].height = 30      # 높이 설정

wb.save('test.xlsx')

In [35]:
from openpyxl import Workbook
import datetime

wb = Workbook()
ws = wb.active

ws['A1'] = 123456789
cell = ws['A1']
cell.number_format = "#,##0_-"
ws.column_dimensions['A'].width = 14

wb.save('test.xlsx')

In [36]:
from openpyxl.styles import PatternFill, Font, colors, Side, Alignment, Border

fill = PatternFill(start_color='eff7f7', fill_type='solid')
ws['A1'].fill = fill

In [37]:
# Font properties
font = Font(name='나눔고딕', size=11, color=colors.RED, italic=True)
ws['A1'].font = font
ws['A1'] = 1234

In [38]:
al = Alignment(horizontal="center", vertical="center")
ws['A1'].alignment = al
wb.save('test.xlsx')

In [39]:
border = Border(left=Side(style='thin'), 
                     right=Side(style='thin'), 
                     top=Side(style='thin'), 
                     bottom=Side(style='thin'))

for row in ws['A1':'C10']:
    for cell in row:
        cell.border = border

In [40]:
ws.merge_cells('A2:D2')
ws.unmerge_cells('A2:D2')

In [41]:
ws.insert_rows(1)  # 첫 행 삽입
ws.insert_cols(1)  # 첫 열 삽입

In [42]:
ws.delete_rows(1,3)  # 첫 행 ~ 셋째 행을 삭제

In [43]:
ws.delete_cols(1,1)  # 첫 열을 삭제

In [44]:
110 * 1.02

112.2

In [45]:
110 * 1.003

110.32999999999998

In [46]:
import numpy as np

np.linspace(1.02, 1.003, 10)

array([1.02      , 1.01811111, 1.01622222, 1.01433333, 1.01244444,
       1.01055556, 1.00866667, 1.00677778, 1.00488889, 1.003     ])

In [47]:
np.random.random(12)

array([0.28064827, 0.33344418, 0.57243427, 0.36441912, 0.28157618,
       0.40199189, 0.7287625 , 0.25220007, 0.88685232, 0.14082582,
       0.99018887, 0.00369844])

In [48]:
ref = [110, 110, 110, 110, 220, 220, 220, 220, 440, 440, 440, 440]
ref * (1+np.random.random(12))

array([177.19719259, 168.4881135 , 159.62804124, 162.43036167,
       322.10454363, 260.68758635, 433.02218316, 351.86238667,
       549.70423061, 693.23476466, 839.58446952, 565.95434512])

In [49]:
import numpy as np

for r in np.linspace(1.02, 1.003, 20):
    freq1 = ref * (1+np.random.random(12))
    freq2 = r * freq1

In [50]:
for r in np.linspace(1.02, 1.003, 20):
    freq1 = ref * (1+np.random.random(12))
    freq2 = r * freq1
    row = []
    for f1, f2 in zip(freq1, freq2):
        t = [f1, f2]
        np.random.shuffle(t)
        row.extend(t)

In [51]:
row

[153.62770144063538,
 153.16819685008514,
 137.92158285931794,
 137.50905569224122,
 136.41009639137508,
 136.81932668054918,
 198.08183826544658,
 198.6760837802429,
 308.2853260294589,
 307.36323632049744,
 368.5095913796453,
 367.40736927182985,
 393.9671733480729,
 392.78880692729103,
 377.9030104914233,
 379.0367195228975,
 575.7066042470434,
 573.984650296155,
 440.81482024419296,
 442.1372647049255,
 626.0819179518319,
 624.2092900815871,
 639.1143770108786,
 641.0317201419111]

In [52]:
import numpy as np
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font, colors, Alignment


def index2cell(row, col):
    return '{}{}'.format(get_column_letter(col), row)

# 워크북 새로 만든다
wb = Workbook()
ws = wb.active

# 설정 변수들
levels = 20
ref = [110, 110, 110, 110, 220, 220, 220, 220, 440, 440, 440, 440]
rows, cols = levels, len(ref)*2

# 스타일 변수들
font = Font(name='Tahoma', size=10, color=colors.DARKBLUE, italic=False)
font_title = Font(name='Tahoma', size=10, color=colors.BLACK, bold=True)

# 첫 행 타이틀을 넣는다
row = ['']*(cols+1)
row[1::2] = ['Q'+str(i+1) for i in range(len(ref))]
row[0] = 'Level'
ws.append(row)
align = Alignment(horizontal="center")

# 한 문제는 두 개의 주파수로 구성된다. 따라서 첫 행의 두 셀을 하나로 합친다.
for i in range(cols//2):
    a = index2cell(1, (i+1)*2)
    b = index2cell(1, (i+1)*2+1)
    ws.merge_cells(a+':'+b)

# 첫 행의 스타일(정렬, 폰트)을 설정한다.
for col in range(cols+1):
    cell = ws.cell(row=1, column=col+1)
    cell.alignment = align
    cell.font = font_title

# 주파수 데이터를 넣는다.
for i, r in enumerate(np.linspace(1.02, 1.003, levels)):
    freq1 = ref * (1+np.random.random(len(ref)))
    freq2 = r * freq1
    row = []
    for f1, f2 in zip(freq1, freq2):
        t = [f1, f2]
        np.random.shuffle(t)
        row.extend(t)
    ws.append([str(i+1)]+row)

# 첫 열의 스타일을 정한다.
for row in range(rows+1):
    cell = ws.cell(row=row+1, column=1)
    cell.alignment = align
    cell.font = font_title

# 주파수 데이터의 스타일을 설정한다.
for row in ws['B2':index2cell(rows+1,cols+1)]:
    for cell in row:
        cell.number_format = '0.000'
        cell.font = font
        
wb.save('data\\pitch_train.xlsx')

## 도전 과제 - CSV 파일을 읽고 엑셀로 저장하기

In [53]:
import pandas as pd

url = "http://samplecsvs.s3.amazonaws.com/Sacramentorealestatetransactions.csv"
df = pd.read_csv(url)  # 웹에서 직접 읽어온다.
df.to_excel('data\\Sacramentorealestatetransactions.xlsx', index=False)

In [54]:
df.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

In [55]:
rows, cols = df.shape
rows, cols

(985, 12)

In [56]:
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font, colors, Side, Alignment, Border
from openpyxl.utils import get_column_letter

def index2cell(row, col):
    return '{}{}'.format(get_column_letter(col), row)

wb = load_workbook('data\\Sacramentorealestatetransactions.xlsx')
ws = wb.active

font = Font(name='Tahoma', size=10, color=colors.DARKBLUE, italic=True)
font2 = Font(name='Tahoma', size=10, color=colors.DARKYELLOW, bold=True)
fill = PatternFill(start_color='eff7f7', fill_type='solid')
border = Border(left=Side(style='thin'), 
                     right=Side(style='thin'), 
                     top=Side(style='thin'), 
                     bottom=Side(style='thin'))

# 폰트 적용
for row in ws['A1':index2cell(rows+1,cols)]:
    for cell in row:
        cell.font = font
        cell.border = border

# 첫 행 배경색 적용
for row in ws['A1':index2cell(1,cols)]:
    for cell in row:
        cell.font = font2
        cell.fill = fill

# 열 폭 적용     
for col in ws.columns:
    try:
        max_len = max([len(cell.value) for cell in col])  # 최대 문자열 길이 계산
    except:
        max_len = 0  # 계산이 안될 때
    width = min(max(6, max_len+2), 28)  # 최소 6 ~ 최대 28 사이의 폭을 지정
    ws.column_dimensions[col[0].column].width = width # col[0].column는 열이름

wb.save('data\\Sacramentorealestatetransactions2.xlsx')